services:
  vision-api:
    build:
      context: .
    container_name: vision_administration_api
    env_file:
      - .env
    environment:
      DB_HOST: ${API_DB_HOST:-host.docker.internal}
      DB_PORT: ${API_DB_PORT:-5432}
    ports:
      - "${API_PORT:-8000}:8000"
    restart: unless-stopped
